### ISSUE TITLE
Why is TranchToken.sol needed? 

### ISSUE THREAD

**Issue by Walodja1987** [nayms/contracts#77]
Hi,

I was going through your code and I was wondering why a modified version of the ERC20 token was implemented under TrancheToken.sol, in particular why the interface IPolicyTranchTokensFacet is needed. For example, you use this modified ERC20 version to create a TrancheToken in PolicyCoreFacet.sol, Line 102: TranchToken t = new TranchToken(address(this), i); 

Could someone explain to a below average solidity developer? Is this because a delegatecall is used in the diamond implementation this operation is not allowed in such cases?

Best
Wladimir

**Comment by hiddentao** [comment]
Thanks for the question.

The `TranchToken` contract is supposed to represent a plain old ERC-20 token contract, and as you noted, is what gets deployed when we wish to deploy a new tranche token. Internally, it calls through to its owing policy for its actual logic because we want the policy to have control over what happens with its tokens, and this then allows us to upgrade the tranch token logic by just upgrading the policy.

Now, regarding the `IPolicyTranchTokensFacet` code. If we were to refer to `PolicyTranchTokens` from within `PolicyCoreFacet` then the entire bytecode of `PolicyTranchTokens` would need to be included in the deployment of `PolicyCoreFacet` - this is generally true for Solidity. In order to avoid this and minimize the final bytecode size we use interfaces throughout our codebase, hence why we have `IPolicyTranchTokensFacet`. 

Note that _coding to an interface_ is a generally accepted and recommended practice when it comes to OOP -> https://medium.com/javarevisited/oop-good-practices-coding-to-the-interface-baea84fd60d3
